"""
Task 3: Testing & Safety
Wrap any AI-generated text through this before showing it to the user.
"""

import json
import time

from shared.gemini_client import call_gemini


class SafetyCheckUnavailable(Exception):
    """Raised when the safety check cannot be performed (e.g., all API keys exhausted)."""
    pass


SAFETY_CHECK_PROMPT = """You are a content safety checker for a social media content creation tool.

Review the following text that was generated by AI for a user's social media post:
"{text}"

Check ONLY for genuinely harmful content:
- Hate speech or discriminatory language
- False medical/health claims (e.g., "cures cancer")
- Spam or scam content
- Sexually explicit material
- Threats or harassment
- Dangerously misleading claims

DO NOT flag content just because it is promotional, exaggerated marketing, or AI-generated.
Marketing language like "best product" or "amazing results" is normal for social media.

Return ONLY valid JSON in this format, nothing else:
{{"safe": true, "reason": ""}}
or
{{"safe": false, "reason": "brief explanation of what was flagged"}}
"""


def is_content_safe(text: str, retries: int = 1) -> dict:
    if not text or not text.strip():
        return {"safe": True, "reason": ""}

    prompt = SAFETY_CHECK_PROMPT.format(text=text.strip())

    last_error = None
    for attempt in range(retries + 1):
        try:
            response = call_gemini(prompt)
            result = json.loads(response.text)
            return {
                "safe": bool(result.get("safe", False)),
                "reason": result.get("reason", ""),
            }

        except RuntimeError as e:
            last_error = e
            break
        except Exception as e:
            last_error = e
            print(f"[safety_check] Attempt {attempt + 1} failed: {e}")
            if attempt < retries:
                time.sleep(3)

    raise SafetyCheckUnavailable(f"Safety check unavailable: {last_error}")


if __name__ == "__main__":
    print(is_content_safe("3 Common Skincare Mistakes Wrecking Your Barrier"))